# Generated by Django 3.2.12 on 2022-04-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='shop',
        ),
    ]
